hyper_params:
  batch_size: 1
  hidden_dim: 32
  learning_rate: 0.001

training:
  epochs: 5
  verbose: True
  log_interval: 1
  save_model: False

paths:
  data_train: train.root
  data_valid: validation.root
  model_dir: model/
  log_dir: log/
  result_dir: result/
  config_dir: config/
  checkpoint_dir: checkpoint/
  checkpoint_name: checkpoint.pth

