hyper_params:
  batch_size: 1
  hidden_dim: 32
  learning_rate: 0.0001
  gamma: 0.7
  epoch_lr_step: 5
  jet_penaltyfactor: 0.1

training:
  epochs: 2
  verbose: True
  log_interval: 1
  save_model: True
  patience: 5

paths:
  data_train: train.root
  data_valid: validation.root
  model: model/JetGNN.pth
  log_dir: model/log/
